def run_analysis():   
    addAnalysis( "Analysis1" )
    addAnalysisCommand( "Analysis1", "NONLIN", "结构非线性" )
    addAnalysisCommandDetail( "Analysis1", "结构非线性", "EXECUT(1)/LOAD/LOADNR" )
    setAnalysisCommandDetail( "Analysis1", "结构非线性", "EXECUT(1)/LOAD/LOADNR", 1 )
    setAnalysisCommandDetail( "Analysis1", "结构非线性", "EXECUT(1)/LOAD/STEPS/EXPLIC/SIZES", "1.00000" )
    setAnalysisCommandDetail( "Analysis1", "结构非线性", "EXECUT(1)/LOAD/STEPS/EXPLIC/SIZES", "0.1(10) 0.2(10) 0.5(10) 1(15)" )
    setAnalysisCommandDetail( "Analysis1", "结构非线性", "EXECUT(1)/ITERAT/MAXITE", 200 )
    setAnalysisCommandDetail( "Analysis1", "结构非线性", "EXECUT(1)/ITERAT/METHOD/METNAM", "SECANT" )
    addAnalysisCommandDetail( "Analysis1", "结构非线性", "EXECUT(1)/ITERAT/CONVER/ENERGY" )
    setAnalysisCommandDetail( "Analysis1", "结构非线性", "EXECUT(1)/ITERAT/CONVER/ENERGY", True )
    setAnalysisCommandDetail( "Analysis1", "结构非线性", "EXECUT(1)/ITERAT/CONVER/DISPLA", False )
    setAnalysisCommandDetail( "Analysis1", "结构非线性", "EXECUT(1)/ITERAT/CONVER/FORCE", False )
    setAnalysisCommandDetail( "Analysis1", "结构非线性", "EXECUT(1)/ITERAT/CONVER/ENERGY/NOCONV", "CONTIN" )
    setAnalysisCommandDetail( "Analysis1", "结构非线性", "EXECUT(1)/ITERAT/CONVER/ENERGY/TOLCON", 0.0001 )
    setAnalysisCommandDetail( "Analysis1", "结构非线性", "EXECUT(1)/ITERAT/CONVER/ENERGY/TOLABT", 10000 )
    setAnalysisCommandDetail( "Analysis1", "结构非线性", "EXECUT(1)/ITERAT/CONVER/ENERGY/TOLCON", 0.0001 )